### PR TITLE
Dependency fetcher

### PR DESCRIPTION
**Pull request by kris701**
Added a dependency fetcher to automatically put dependencies where the rest of the toolchain would expect it

### CODE REVIEW

**Comment by jamadaha** [comment]
Seems not to do anything, but I might just not be running it?

Did `dotnet build` and `dotnet run` from root and dependencies is still empty.

Log:
```
xxxx@ST1:~/Documents/GitHub/P9$ dotnet build
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  ToolchainTests -> /home/xxxx/Documents/GitHub/P9/ToolchainTests/bin/Debug/net7.0/ToolchainTests.dll
/home/xxxx/Documents/GitHub/P9/Tools/ProjectHelper.cs(14,20): warning CS8602: Dereference of a possibly n
ull reference. [/home/xxxx/Documents/GitHub/P9/Tools/Tools.csproj]
  Tools -> /home/xxxx/Documents/GitHub/P9/Tools/bin/Debug/net7.0/Tools.dll
  DependencyFetcher -> /home/xxxx/Documents/GitHub/P9/DependencyFetcher/bin/Debug/net7.0/DependencyFetche
r.dll
  PlanSampleGenerator -> /home/xxxx/Documents/GitHub/P9/PlanSampleGenerator/bin/Debug/net7.0/PlanSampleGe
nerator.dll
  Toolchain -> /home/xxxx/Documents/GitHub/P9/Toolchain/bin/Debug/net7.0/Toolchain.dll

Build succeeded.
```

**Comment by kris701** [comment]
Im pretty sure you are just compiling it, at not actually running it

**Comment by jamadaha** [comment]
Ah, now gives error
```
/home/xxxx/Documents/GitHub/P9/Tools/ProjectHelper.cs(14,20): warning CS8602: Dereference of a possibly n
ull reference. [/home/xxxx/Documents/GitHub/P9/Tools/Tools.csproj]
Unhandled exception. System.IO.IOException: File not found: ../../../../Dependencies/dependencies.json
   at DependencyFetcher.DependencyChecker..ctor(String dependencyFile) in /home/xxxx/Documents/GitHub/P9/
DependencyFetcher/DependencyChecker.cs:line 20
   at DependencyFetcher.Program.Main(String[] args) in /home/xxxx/Documents/GitHub/P9/DependencyFetcher/P
rogram.cs:line 9
```

**Comment by kris701** [comment]
There we go, think it works a bit better with the cli args now :)

**Comment by jamadaha** [comment]
Seems to work some of time to some extent.

**Review by jamadaha — APPROVED** [review]

**Pull request merged**
